# Aauu Mob Capital (AMC) - 主配置文件
# 版本: 2.0

# 数据库设置
database:
  type: sqlite
  # SQLite数据库文件路径（相对于插件文件夹）
  file: data/amc.db

# 经济设置
economy:
  # 是否启用经济功能（需要Vault）
  enabled: true

# 刷怪笼数量限制和购买设置
limits:
  normal:
    # 基础数量限制
    base: 5
    # 购买设置
    purchase:
      enabled: true  # 是否允许购买额外位置
      base_price: 1000.0  # 基础价格（购买第1个额外位置的价格）
      price_mode: "multiplier"  # 价格模式: "fixed"(固定价格) 或 "multiplier"(倍率递增)
      price_multiplier: 1.2  # 价格倍率（仅在multiplier模式下生效，每次购买后价格乘以此倍率）
      max_purchasable: 50  # 最多可购买的额外位置数
  
  premium:
    # 基础数量限制
    base: 2
    # 购买设置
    purchase:
      enabled: true  # 是否允许购买额外位置
      base_price: 5000.0  # 基础价格（购买第1个额外位置的价格）
      price_mode: "multiplier"  # 价格模式: "fixed"(固定价格) 或 "multiplier"(倍率递增)
      price_multiplier: 1.5  # 价格倍率（仅在multiplier模式下生效，每次购买后价格乘以此倍率）
      max_purchasable: 20  # 最多可购买的额外位置数

# 刷怪机制设置
spawning:
  # 默认生成数量（每波）
  default_spawn_count: 1
  # 默认生成间隔（tick，20 tick = 1秒）
  default_spawn_delay: 100
  # 默认最大附近实体数
  default_max_nearby_entities: 6
  # 默认激活范围（方块）
  default_activation_range: 16
  # 最大存储设置
  storage:
    enabled: true
    # 默认最大存储容量
    default_max_storage: 100
    # 默认存储时间（秒）
    default_storage_time: 3600
    # 存储释放间隔（tick）
    release_interval: 20

# 刷怪笼自定义名称设置
spawner_names:
  # 是否启用自定义名称功能
  enabled: true
  # 默认刷怪笼名称格式（当未设置自定义名称时使用）
  # 可用变量: %type% (类型), %entity% (实体名称)
  default_format: "§6%type% 刷怪笼"
  # 自定义名称配置
  # 格式: "类型_实体名": "自定义显示名称"
  custom_names:
    NORMAL_ZOMBIE: "§a僵尸生成器"
    NORMAL_SKELETON: "§f骷髅生成器"
    PREMIUM_ZOMBIE: "§6高级僵尸生成器"
    PREMIUM_BLAZE: "§c烈焰人生成器"

# 刷怪笼默认实体设置
default_entities:
  # 当使用 /amc give 命令不指定实体时的默认实体
  normal: ZOMBIE
  premium: ZOMBIE

# 性能优化设置
performance:
  # 刷怪笼处理间隔（tick）
  spawner_tick_interval: 20
  # 每tick处理的最大刷怪笼数量
  max_spawners_per_tick: 10
  # 是否使用异步处理
  async_processing: true

# PlaceholderAPI设置
placeholderapi:
  # 是否启用PAPI支持
  enabled: true

# 调试模式
debug: false
