name: MonsterCapitalWorks
version: '2.1'
main: org.mcw.monstercapitalworks.MonsterCapitalWorks
api-version: '1.21'
authors: [ Aauu ]
description: Monster Capital Works (MCW) - 高级刷怪笼管理系统
depend: [Vault]
softdepend: [PlaceholderAPI]
load: POSTWORLD

commands:
  mcw:
    description: mcw主命令
    usage: /mcw <help|reload|give|info|list|remove>
    aliases: [monstercapitalworks, capitalworks]

permissions:
  mcw.*:
    description: 所有MCW权限
    children:
      mcw.create.*: true
      mcw.gui.*: true
      mcw.bypass.*: true
      mcw.admin: true
  
  mcw.create.*:
    description: 创建所有类型刷怪笼
    children:
      mcw.create.normal: true
      mcw.create.premium: true
  
  mcw.create.normal:
    description: 创建普通刷怪笼
    default: true
  
  mcw.create.premium:
    description: 创建付费刷怪笼
    default: false
  
  mcw.gui.*:
    description: 打开所有GUI
    children:
      mcw.gui.normal: true
      mcw.gui.premium: true
      mcw.gui.purchase: true
  
  mcw.gui.normal:
    description: 打开普通刷怪笼GUI
    default: true
  
  mcw.gui.premium:
    description: 打开付费刷怪笼GUI
    default: false
  
  mcw.gui.purchase:
    description: 打开购买界面
    default: true
  
  mcw.bypass.*:
    description: 绕过所有限制
    children:
      mcw.bypass.conditions: true
      mcw.bypass.disabled: true
      mcw.bypass.limits: true
  
  mcw.bypass.conditions:
    description: 绕过生物生成条件
    default: op
  
  mcw.bypass.disabled:
    description: 绕过生物禁用限制
    default: op
  
  mcw.bypass.limits:
    description: 绕过所有数量限制
    default: op
  
  mcw.admin:
    description: 所有管理员权限
    default: op
    children:
      mcw.admin.reload: true
      mcw.admin.give: true
      mcw.admin.remove: true
      mcw.admin.break: true
      mcw.admin.use: true
      mcw.admin.pickup: true
      mcw.admin.list.others: true
      mcw.admin.limit: true
  
  mcw.admin.reload:
    description: 重载配置权限
    default: op
  
  mcw.admin.give:
    description: 给予刷怪笼权限
    default: op
  
  mcw.admin.remove:
    description: 移除刷怪笼权限
    default: op
  
  mcw.admin.break:
    description: 破坏他人刷怪笼权限
    default: op
  
  mcw.admin.use:
    description: 使用他人刷怪笼权限
    default: op
  
  mcw.admin.pickup:
    description: 拾取任何玩家的刷怪笼权限
    default: op
  
  mcw.admin.list.others:
    description: 查看他人刷怪笼列表权限
    default: op
  
  mcw.place.*:
    description: 放置所有类型刷怪笼
    children:
      mcw.place.normal: true
      mcw.place.premium: true
  
  mcw.place.normal:
    description: 放置普通刷怪笼
    default: true
  
  mcw.place.premium:
    description: 放置付费刷怪笼
    default: false
  
  mcw.spawnmode.precise:
    description: 使用精确生成模式
    default: false
  
  mcw.admin.limit:
    description: 管理玩家刷怪笼限制
    default: op
